### ISSUE TITLE
Not all address fields included in the form

### ISSUE THREAD

**Issue by paulnagle** [nigel-bmlt/meeting-admin-workflow#11]
In the form to update the meeting, not all of the available address fields are available.

i.e. County/Sub-Province and Nation 

In my region, we cover 2 separate Countries (Ireland and Northern Ireland) so we do use the Nation field.
And the country is divided up into Counties, so we use the County field as well.

**Comment by nigel-bmlt** [comment]
Support for these specific fields have been added in 0.3-beta. Will look at adding a more generic method for handling these shortly, as these aren't the only fields I've missed.
