### ISSUE TITLE
geolocate fails on good address

### ISSUE THREAD

**Issue by cdiddy1979** [nigel-bmlt/meeting-admin-workflow#14]
When clicking "approve" in Workflow Submissions, error reads as follows:
"ERROR: Could not geolocate meeting address. Please try amending the address with additional/correct details.."

But the lat/long are filled out, and they are correct.

**Comment by nigel-bmlt** [comment]
hey there!

Our issues site lives here: https://github.com/bmlt-enabled/bmlt-workflow/issues

I've opened a new issue to track this over there - https://github.com/bmlt-enabled/bmlt-workflow/issues/145
